# Generated by Django 5.1.1 on 2024-09-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_user_rename_date_event_duedate_criteria_aspect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='criteria',
        ),
    ]
