# Generated by Django 5.1.1 on 2024-09-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_remove_task_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='criteria',
        ),
        migrations.AddField(
            model_name='aspect',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='rate.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
