# Generated by Django 5.1.1 on 2024-09-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_remove_aspect_criteria_aspect_event_delete_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='feedback',
        ),
        migrations.AddField(
            model_name='user',
            name='resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rate.resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='aspect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='rate.aspect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='resource',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='rate.resource'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
