# Generated by Django 5.1.1 on 2024-09-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_remove_usertask_task_remove_usertask_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='rate.event'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='rate.resource'),
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.aspect')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTask',
        ),
    ]
