# Generated by Django 5.1.1 on 2024-09-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_alter_resource_event_alter_user_resource_userscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='resource',
        ),
        migrations.AddConstraint(
            model_name='userscore',
            constraint=models.UniqueConstraint(fields=('user', 'resource', 'aspect'), name='unique_user_resource_aspect'),
        ),
    ]
