# Generated by Django 5.1.1 on 2024-09-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_remove_user_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.event'),
            preserve_default=False,
        ),
    ]
