# Generated by Django 5.1.1 on 2024-09-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0009_resource_uploaded_at_alter_aspect_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscore',
            name='event',
        ),
    ]
