# Generated by Django 5.1.1 on 2024-10-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0011_alter_userscore_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='name',
            field=models.CharField(default='Default name', max_length=100),
        ),
    ]
