# Generated by Django 5.1.1 on 2024-10-27 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0013_remove_resource_file_url_resource_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='file',
            new_name='resource_file',
        ),
    ]
