# Generated by Django 5.1.1 on 2024-11-09 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0014_rename_file_resource_resource_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userscore',
            name='unique_user_resource_aspect',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='aspect',
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='score',
        ),
    ]
