# Generated by Django 5.1.1 on 2024-11-09 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0016_userresource_delete_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresource',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
