# Generated by Django 5.1.1 on 2024-11-10 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0017_userresource_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresource',
            unique_together={('user', 'resource')},
        ),
    ]
