# Generated by Django 5.1.3 on 2024-11-19 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0018_alter_userresource_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourceAspectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.aspect')),
                ('user_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='rate.userresource')),
            ],
            options={
                'unique_together': {('user_resource', 'aspect')},
            },
        ),
    ]
