# Generated by Django 5.1.3 on 2024-11-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0019_userresourceaspectscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
