# Generated by Django 5.1.3 on 2024-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0021_alter_resource_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspect',
            name='percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userresourceaspectscore',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
