# Generated by Django 5.1.3 on 2024-11-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_avater_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='realname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
