# Generated by Django 5.1.3 on 2024-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_realname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='realname',
            field=models.CharField(blank=True, default='未命名用户', max_length=100, null=True),
        ),
    ]
