# Generated by Django 5.1.4 on 2024-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cat',
            field=models.CharField(blank=True, default='no cat', max_length=100, null=True),
        ),
    ]
